include:
  - project: 'full-stack/templates/gradle-ci-template'
    ref: v1.3
    file:
      - /templates/gradle.gitlab-ci.yml

stages:
  - test
  - publish

test-unit:
  stage: test
  extends: .gradle-unit-test

publish:
  stage: publish
  extends: .gradle-publish

publish-contract:
  image: $GRADLE_IMAGE
  when: manual
  script:
    - echo "Publishing with $VERSION_OPTS"
    - chmod +x ./gradlew
    - ./gradlew $JAVA_OPTS $VERSION_OPTS :graph-contract:build
    - ./gradlew $JAVA_OPTS $VERSION_OPTS :graph-contract:assemble
    - ./gradlew $JAVA_OPTS $VERSION_OPTS :graph-contract:publish

publish-snapshot:
  stage: publish
  extends: .gradle-publish-snapshot
