include:
  - project: 'full-stack/templates/gradle-ci-template'
    ref: v1.3
    file:
      - /templates/gradle.gitlab-ci.yml

stages:
  - test
  - publish

test-unit:
  stage: test
  extends: .gradle-unit-test

publish:
  stage: publish
  extends: .gradle-publish

publish-snapshot:
  stage: publish
  extends: .gradle-publish-snapshot
